MCServerManager/MCServerManager/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MCServerManager.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

MCServerManager/MCServerManager/Pages/ChatRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MCServerManager.Pages
{
    public class ChatRoomModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MCServerManager/MCServerManager/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MCServerManager.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

MCServerManager/MCServerManager/Pages/CreateServer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MCServerManager;
using System.IO;

namespace MCServerManager.Pages
{
    public class CreateServerModel : PageModel
    {
        private readonly MCServerContext _db;

        public CreateServerModel(MCServerContext db)
        {
            _db = db;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public MCServer MCServer { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.AddMCServer(MCServer);

            if(MCServer.CreateDirectory && !Directory.Exists(MCServer.Folder))
            {
                MCServer.MakeDirectory(MCServer.Folder);
            }

            return RedirectToPage("./Index");
        }

    }
}

MCServerManager/MCServerManager/Pages/EditServer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MCServerManager;


namespace MCServerManager.Pages
{
    public class EditServerModel : PageModel
    {
        private readonly MCServerContext _db;

        public EditServerModel(MCServerContext db)
        {
            _db = db;
        }

        [BindProperty]
        public MCServer MCServer { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            MCServer = _db.FindMCServer((int)id);

            if (MCServer == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }           

            try
            {
                _db.UpdateMCServer(MCServer);
                MCServerManagerClass.Instance.UpdateServer(MCServer);
            }
            catch (Exception e)
            {
                throw e;
            }

            return RedirectToPage("./Index");
        }
    }
}

MCServerManager/MCServerManager/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MCServerManager.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MCServerManager/MCServerManager/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MCServerManager.Pages
{
    public class IndexModel : PageModel
    {
        private readonly MCServerContext _db;

        public IList<MCServer> MCServer { get; set; }
        public IList<int> ActiveServerIds { get; set; }

        public IndexModel(MCServerContext db)
        {
            _db = db;
        }

        public void OnGet()
        {
            MCServer = _db.GetAllMCServers();
            ActiveServerIds = MCServerManagerClass.Instance.GetActiveServers().Select(x => x.Id).ToList();
        }

        public IActionResult OnPostDelete(int id)
        {
            var server = _db.FindMCServer(id);
            if (!string.IsNullOrEmpty(server.Name))
            {
                _db.RemoveMCServer(id);
            }
            return RedirectToPage();
        }
    }
}

MCServerManager/MCServerManager/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MCServerManager.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MCServerManager/MCServerManager/Pages/ServerDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MCServerManager;
using MCServerManager.Hubs;
using Microsoft.AspNetCore.SignalR;
using System.Threading;
using System.IO;

namespace MCServerManager.Pages
{
    public class ServerDetailModel : PageModel
    {
        private readonly MCServerContext _db;
        private readonly IHubContext<ServerHub> _serverHub;

        public ServerDetailModel(MCServerContext db, IHubContext<ServerHub> serverHub)
        {
            _db = db;
            _serverHub = serverHub;
        }
        public string Filename { get; set; }
        public string Folder { get; set; }
        public int ServerId { get; set; }
        public MCServer MCServer { get; set; }

        public bool IsActive
        {
            get
            {
                if(MCServer == null)
                {
                    return false;
                }
                return MCServerManagerClass.Instance.GetActiveById(MCServer.Id);
            }
        }

        public IActionResult OnGet(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }


            MCServer = _db.FindMCServer((int)id);

            if (MCServer.Name == null)
            {
                return NotFound();
            }
            return Page();
        }

        public void OnPostStart(int id)
        {
            var server = _db.FindMCServer(id);
            server._serverHub = this._serverHub;
            if (!string.IsNullOrEmpty(server.Name) && !MCServerManagerClass.Instance.GetActiveById(id))
            {
                MCServerManagerClass.Instance.AddServer(server);
                MCServerManagerClass.Instance.StartServerById(id);
            }
            MCServer = server;
        }

    }
}

MCServerManager/MCServerManager/Pages/ServerList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MCServerManager;


namespace MCServerManager.Pages
{
    public class ServerListModel : PageModel
    {
        private readonly MCServerContext _db;

        public ServerListModel(MCServerContext db)
        {
            _db = db;
        }

        public IList<MCServer> MCServer { get;set; }

        public void OnGet()
        {
            MCServer = _db.GetAllMCServers();
        }
    }
}

MCServerManager/MCServerManager/Pages/Settings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MCServerManager;

namespace MCServerManager.Pages
{
    public class SettingsModel : PageModel
    {
        public SettingsModel()
        {
        }

        [BindProperty]
        public Settings Settings { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {

            Settings = Settings.LoadSettings();

            if (Settings == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                Settings.SaveSettings();
            } catch (Exception e)
            {

            }

            return RedirectToPage("./Index");
        }
    }
}

MCServerManager/MCServerManager/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

MCServerManager/MCServerManager/Pages/ChatRoom.cshtml
@page
<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            User..........<input type="text" id="userInput" />
            <br />
            Message...<input type="text" id="messageInput" />
            <input type="button" id="sendButton" value="Send Message" />
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-6">&nbsp;</div>
        <div class="col-6">
            <ul id="messagesList"></ul>
        </div>
    </div>
</div>

<script src="~/lib/@@aspnet/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

MCServerManager/MCServerManager/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MCServerManager/MCServerManager/Pages/CreateServer.cshtml
@page
@model MCServerManager.Pages.CreateServerModel

@{
    ViewData["Title"] = "CreateServer";
}

<h2>CreateServer</h2>

<h4>MCServer</h4>
<hr />
<div class="row">
    <div @*class="col-md-4" *@>
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <button type="button" class="collapsible"><h4>More Details</h4></button>
            <div class="content" style="padding: 10px">
                <label asp-for="MCServer.CreateDirectory" class="control-label"></label>
                <input type="checkbox" asp-for="MCServer.CreateDirectory" />
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Name" class="control-label"></label>
                <input asp-for="MCServer.Name" class="form-control" />
                <span asp-validation-for="MCServer.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Modpack" class="control-label"></label>
                <input asp-for="MCServer.Modpack" class="form-control" />
                <span asp-validation-for="MCServer.Modpack" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Port" class="control-label"></label>
                <input asp-for="MCServer.Port" class="form-control" />
                <span asp-validation-for="MCServer.Port" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.MaxRam" class="control-label"></label>
                <input asp-for="MCServer.MaxRam" class="form-control" />
                <span asp-validation-for="MCServer.MaxRam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Jar" class="control-label"></label>
                <input asp-for="MCServer.Jar" class="form-control" />
                <span asp-validation-for="MCServer.Jar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Folder" class="control-label"></label>
                <input asp-for="MCServer.Folder" class="form-control" />
                <span asp-validation-for="MCServer.Folder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MCServerManager/MCServerManager/Pages/EditServer.cshtml
@page
@model MCServerManager.Pages.EditServerModel

@{
    ViewData["Title"] = "EditServer";
}

<h2>EditServer</h2>

<h4>MCServer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MCServer.Id" />
            <div class="form-group">
                <label asp-for="MCServer.Name" class="control-label"></label>
                <input asp-for="MCServer.Name" class="form-control" />
                <span asp-validation-for="MCServer.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Modpack" class="control-label"></label>
                <input asp-for="MCServer.Modpack" class="form-control" />
                <span asp-validation-for="MCServer.Modpack" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Port" class="control-label"></label>
                <input asp-for="MCServer.Port" class="form-control" />
                <span asp-validation-for="MCServer.Port" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.MaxRam" class="control-label"></label>
                <input asp-for="MCServer.MaxRam" class="form-control" />
                <span asp-validation-for="MCServer.MaxRam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Jar" class="control-label"></label>
                <input asp-for="MCServer.Jar" class="form-control" />
                <span asp-validation-for="MCServer.Jar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCServer.Folder" class="control-label"></label>
                <input asp-for="MCServer.Folder" class="form-control" />
                <span asp-validation-for="MCServer.Folder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MCServerManager/MCServerManager/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Minecraft Server Manager";
}


<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Active
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MCServer[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MCServer[0].Modpack)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MCServer[0].Port)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MCServer[0].MaxRam)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MCServer[0].Jar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MCServer[0].Folder)
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.MCServer)
            {
                <tr>
                    <td>
                        @{ 
                            string green = "#4cff00";
                            string red = "#ff0000";
                            var active = Model.ActiveServerIds.Contains(item.Id);
                            string color = (active) ? green : red;
                        }
                        <span style="height: 25px; width: 25px; background-color: @color; border-radius: 50%; display: inline-block;"></span>
                    </td>
                    <td>
                        <a asp-page="./ServerDetail" asp-route-id="@item.Id">@item.Name</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modpack)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Port)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaxRam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Jar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Folder)
                    </td>
                    <td width="12%">
                        @if (!active)
                        {
                            <a asp-page="./EditServer" asp-route-id="@item.Id" class="btn btn-default">Edit</a>
                        }
                        <button type="submit" style="float: right;" asp-page-handler="delete" asp-route-id="@item.Id" class="btn btn-default">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

MCServerManager/MCServerManager/Pages/ServerDetail.cshtml
@page
@model ServerDetailModel

@{
    ViewData["Title"] = "ServerDetail";
}

@{
    string green = "#4cff00";
    string red = "#ff0000";
    var active = Model.IsActive;
    string color = (active) ? green : red;
}
<span style="height: 25px; width: 25px; background-color: @color; border-radius: 50%; display: inline-block;" id="statusSymbol"></span>
<h2 style="display: inline-block;">Server: @Model.MCServer.Name</h2>

<div>
    <form method="post" class="myButtonArea">
        <input type="submit" class="btn btn-default myButton" asp-page-handler="Start" asp-route-id="@Model.MCServer.Id" value="Start" />
        <input type="button" id="restartButton" value="Restart" class="btn btn-default" />
        <input type="button" id="stopButton" value="Stop" class="btn btn-default" />
        @*<input type="button" id="stopButton1" value="Stop" class="btn btn-default" style="float: right;" /> EXAMPLE FOR NON ESSENTIAL BUTTONS*@
        <a asp-action="Download" asp-route-id="@Model.MCServer.Id" asp-route-folder="@Model.MCServer.Folder" asp-route-filename="/logs/serverLatest.log" id="downloadLog" class="btn btn-default" style="float: right;">Latest Log</a>
    </form>
    <form>

    </form>
</div>

<button class="collapsible"><h4>More Details</h4></button>
<div class="content">
    <form method="post" enctype="multipart/form-data" action="/Home/UploadServerZip">
        <div>
            <p>Upload one or more files using this form:</p>
            <input type="hidden" name="filename" id="FileName" value="" />
            <input type="hidden" name="folder" id="Folder" value="@Model.MCServer.Folder" />
            <input type="hidden" name="serverId" id="ServerId" value="@Model.MCServer.Id" />
            <input type="file" name="files" accept=".zip" onchange="document.getElementById('FileName').value = this.value; this.form.submit();" />
        </div>
        <div>
            @*<input type="submit" value="Upload" />*@
        </div>
    </form>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MCServer.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MCServer.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MCServer.Modpack)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MCServer.Modpack)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MCServer.Port)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MCServer.Port)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MCServer.MaxRam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MCServer.MaxRam)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MCServer.Jar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MCServer.Jar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MCServer.Folder)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MCServer.Folder)
        </dd>
    </dl>
</div>
<div id="serverOutputArea" style="overflow: auto; height: 500px; width:inherit;">
    @foreach (var line in Model.MCServer.Log)
    {
        <br />
        @line
    }
</div>
<div>
    <div class="container">
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="col-10">&nbsp;</div>
            <div class="col-10">
                <label style="display: inline-block; padding-right: 5px">Command:</label><input style="display: inline-block; width: 500px" type="text" id="commandInput" />
                <input type="button" id="sendButton" value="Send Command" />
            </div>
        </div>
    </div>
</div>
<script src="~/lib/@@aspnet/signalr/dist/browser/signalr.js"></script>
<script src="~/js/serverDetails.js"></script>

MCServerManager/MCServerManager/Pages/ServerList.cshtml
@page
@model MCServerManager.Pages.ServerListModel

@{
    ViewData["Title"] = "ServerList";
}

<h2>ServerList</h2>

<p>
    <a asp-page="CreateServer">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MCServer[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCServer[0].Modpack)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCServer[0].Port)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCServer[0].MaxRam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCServer[0].Jar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCServer[0].Folder)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.MCServer) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modpack)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Port)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxRam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Folder)
            </td>
            <td>
                <a asp-page="./EditServer" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./ServerDetail" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MCServerManager/MCServerManager/Pages/Settings.cshtml
@page
@model MCServerManager.Pages.SettingsModel

@{
    ViewData["Title"] = "Settings";
}

<h2>Settings</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Settings.DefaultPath" class="control-label"></label>
                <input asp-for="Settings.DefaultPath" class="form-control" />
                <span asp-validation-for="Settings.DefaultPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.DefaultVanilla" class="control-label"></label>
                <input asp-for="Settings.DefaultVanilla" class="form-control" />
                <span asp-validation-for="Settings.DefaultVanilla" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.DefaultForge" class="control-label"></label>
                <input asp-for="Settings.DefaultForge" class="form-control" />
                <span asp-validation-for="Settings.DefaultForge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}